version: '3'

services:
  app:
    container_name: app
    build: 
      context: node
    entrypoint: wait-for db:3306 -t 40 -- node index.js
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "3001:3001"
    depends_on:
      - db
    networks:
      - app
  
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app

  nginx:
    container_name: nginx
    build:
      context: nginx
    ports:
      - "8080:80"
    networks:
      - app
    depends_on:
      - app

networks:
  app:
    driver: bridge
    